### PR TITLE
Fixed bug where lookahead sets were always being turned into individu…

### PR DESCRIPTION
**Pull request by bnsh**
Fixed bug where lookahead sets were always being turned into individual characters.

Shouldn't _both_ of these succeed? Instead:

```
binesh@p1gen2:/tmp/plipy-code/chap02/lookahead$ python3 ./lookahead.py < grammar-listing26.txt 
[('exp', {'+'}, ['+', 'exp', 'exp']),
 ('exp', {'y', 'x'}, ['term']),
 ('term', {'y', 'x'}, ['var', 'suffix']),
 ('suffix', {'('}, ['(', 'exp', ')']),
 ('suffix', {''}, ['']),
 ('var', {'x'}, ['x']),
 ('var', {'y'}, ['y'])]
binesh@p1gen2:/tmp/plipy-code/chap02/lookahead$ python3 ./lookahead.py < grammar-listing26-bb.txt 
Error: common prefix a for nonterminal var
```

I think this is because on [Line 94 in plipy-code/chap02/lookahead.py](https://github.com/bnsh/plipy-code/blob/4ba8c9cd29dd5ef929e9519310d94efdca4ef4bd/chap02/lookahead/lookahead.py#L94) 

```python3
    GL.append((A, set(S), rule_body))
```

should instead be

```python3
    GL.append((A, set([S]), rule_body))
```

What seems to be happening, is `set(S)` when S is a string, is getting turned into their individual _characters_. It seems to me, that what we want in the set, is the whole token, ("alpha", "beta" in my `var` modification of listing 2.6. Is this so? If so, please accept my pull request.

If not.. Can you please tell me what my misunderstanding is? Thanks!

[grammar-listing26.txt](https://github.com/user-attachments/files/16104270/grammar-listing26.txt)
[grammar-listing26-bb.txt](https://github.com/user-attachments/files/16104271/grammar-listing26-bb.txt)

### CODE REVIEW

**Comment by lutzhamel** [comment]
Hello, thank you for submitting the PR.  I developed the lookahead program in the context of grammars with single character symbols and consequently never tested it with multi-character symbols.

Please do the following before I can accept this PR:

1. There is a similar situation to what you described for line 94 on line 76 of lookahead.py, if you could also fix that that would be appreciated.
2. Please remove all files from your PR (such as readme's, test files etc) that are not actual bugfix code.  Only submit actual bugfix code in your PR.

Once I receive the updated PR I will approve it.

Thanks again.

**Comment by bnsh** [comment]
OK, done! Thanks! (A colleague of mine and I bought your book, and are working our way through it.. Thank _you_ for the book, and all this material!)

**Comment by lutzhamel** [comment]
Again, thank you for taking the time to submit a PR and also for reading my book.  Best, Lutz

**Comment by lutzhamel** [comment]
I will merge that PR and then propagate the fix through the online resources over the next couple of days!

**Pull request merged**
